apiVersion: v1
kind: Service
metadata:
  name: dronewebservice-src
spec:
  selector:
    app: dronewebservice-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP        
    port: 5000             
    targetPort: 8000
    nodePort: 31110