apiVersion: v1
kind: Service
metadata:
  name: dronewebservice-src
spec:
  selector:
    app: dronewebservice-deployment
  ports:     
    - port: 9000             
      targetPort: 8180
  # type: LoadBalancer
  type: NodePort