apiVersion: v1
kind: Service
metadata:
  name: dronewebservice-src
spec:
  selector:
    app: dronewebservice-deployment
  ports:     
    - port: 8080             
      targetPort: 8080
  # type: LoadBalancer
  type: NodePort