#!/bin/bash
echo -e "$DEBUG_IDENTIFICATOR Start docker building script for soft version - $VERSION"

echo -e "$DEBUG_IDENTIFICATOR Preparing system parameters"

DEBUG_IDENTIFICATOR="[ \033[32m DEBUG \033[0m ]"
VERSION=$(cat VERSION)
ROOT_PATH=$(git rev-parse --show-toplevel)

echo -e "$DEBUG_IDENTIFICATOR Reading parameters for docker_build script"

while [ -n "$1" ]
do
case "$1" in
-type) TYPE="$2" 
echo "Found the -type option, with parameter value $TYPE" 
shift ;;
--) shift
break ;;
*) echo "$1 is not an option";;
esac
shift
done

BUILD_PATH="$ROOT_PATH/build/$TYPE/"
IMAGE_NAME="$TYPE"

echo -e "$DEBUG_IDENTIFICATOR Building images"

docker build -t $IMAGE_NAME:$VERSION --file ${BUILD_PATH}Dockerfile .

echo -e "$DEBUG_IDENTIFICATOR Cleaning workspace"

cd $ROOT_PATH

git clean -f -x -d *

echo -e "$DEBUG_IDENTIFICATOR Finish building script"

