#!/bin/bash

DEBUG_IDENTIFICATOR="[ \033[32m DEBUG \033[0m ]"
VERSION=$(cat VERSION)

echo -e "$DEBUG_IDENTIFICATOR Start iptables setup script for soft version - $VERSION"

echo -e "$DEBUG_IDENTIFICATOR Reading parameters for iptables_setup script"
ROOT_PATH=$(git rev-parse --show-toplevel)
CONTROL_PORT=$(cat $ROOT_PATH/config/dronewebservice.conf.yaml | yq '.http.port')
DRONES_NUM=$(cat config/dronewebservice.conf.yaml | yq '.drones | length')

echo -e "$DEBUG_IDENTIFICATOR Setup iptables for control panel"

sudo iptables -t filter -A INPUT -p tcp --dport $CONTROL_PORT -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport $CONTROL_PORT -j ACCEPT

echo -e "$DEBUG_IDENTIFICATOR Setup iptables for drones"

BASE_PORT=($(yq '.drones[].drone.baseport' $ROOT_PATH/config/dronewebservice.conf.yaml))
PORT_NUMBERS=($(yq '.drones[].drone.numberOfPorts' $ROOT_PATH/config/dronewebservice.conf.yaml))
PORT_TYPE=($(yq '.drones[].drone.type' $ROOT_PATH/config/dronewebservice.conf.yaml))

for (( j=0; j < $DRONES_NUM; j++ ))
do
    for (( i=${BASE_PORT[$j]}; i <= ${BASE_PORT[$j]} + ${PORT_NUMBERS[$j]}; i++ ))
    do
    type=$(echo ${PORT_TYPE[$j]} | tr -d '"')
    # echo $type
    sudo iptables -t filter -A INPUT -p $type --dport $i -j ACCEPT
    sudo iptables -t filter -A OUTPUT -p $type --dport $i -j ACCEPT
    done
done

echo -e "$DEBUG_IDENTIFICATOR Show iptables rules"

sudo iptables -L

echo -e "$DEBUG_IDENTIFICATOR End iptables setup"