#!/bin/bash

DEBUG_IDENTIFICATOR="[ \033[32m DEBUG \033[0m ]"
VERSION=$(cat VERSION)

echo -e "$DEBUG_IDENTIFICATOR Start k8s building script for soft version - $VERSION"

echo -e "$DEBUG_IDENTIFICATOR Preparing system parameters"

ROOT_PATH=$(git rev-parse --show-toplevel)
SCRIPTS_PATH=${ROOT_PATH}/scripts
DEPLOYMENT_PATH=${ROOT_PATH}/deployments

echo -e "$DEBUG_IDENTIFICATOR Reading parameters for docker_build script"

while [ -n "$1" ]
do
case "$1" in
-client_examples_numbers) TYPE="$2" 
echo "Found the -type option, with parameter value $TYPE" 
shift ;;
--) shift
break ;;
*) echo "$1 is not an option";;
esac
shift
done

echo -e "$DEBUG_IDENTIFICATOR Build docker images"


${SCRIPTS_PATH}/docker_build -type droneclient

${SCRIPTS_PATH}/docker_build -type dronewebservice

echo -e "$DEBUG_IDENTIFICATOR Start cluster in minikube"

minikube start

echo -e "$DEBUG_IDENTIFICATOR Create namespace dronewebservice in minikube"

kubectl create namespace dronewebservice

echo -e "$DEBUG_IDENTIFICATOR Get info about cluster"

kubectl cluster-info

echo -e "$DEBUG_IDENTIFICATOR Set namespace=dronewebservice in current context"

kubectl config set-context --current --namespace=dronewebservice

echo -e "$DEBUG_IDENTIFICATOR View config of cluster"

kubectl config view

echo -e "$DEBUG_IDENTIFICATOR Set IP adress of cluster in custom config"

# kubectl get nodes -o json | jq '.items[0].status.addresses[0].address'

echo -e "$DEBUG_IDENTIFICATOR Apply dronewebservice deployments"

# kubectl apply -f ${DEPLOYMENT_PATH}/dronewebservice/deployment.yaml --kubeconfig scripts/kube/config

# kubectl get deployments

echo -e "$DEBUG_IDENTIFICATOR Build kubernetes images"

echo -e "$DEBUG_IDENTIFICATOR End k8s building script"