#!/bin/bash

DEBUG_IDENTIFICATOR="[ \033[32m DEBUG \033[0m ]"
VERSION=$(cat VERSION)

echo -e "$DEBUG_IDENTIFICATOR Start k8s building script for soft version - $VERSION"

echo -e "$DEBUG_IDENTIFICATOR Preparing system parameters"

ROOT_PATH=$(git rev-parse --show-toplevel)
SCRIPTS_PATH=${ROOT_PATH}/scripts
DEPLOYMENT_PATH=${ROOT_PATH}/deployments

echo -e "$DEBUG_IDENTIFICATOR Reading parameters for docker_build script"

while [ -n "$1" ]
do
case "$1" in
-client_examples_numbers) TYPE="$2" 
echo "Found the -type option, with parameter value $TYPE" 
shift ;;
--) shift
break ;;
*) echo "$1 is not an option";;
esac
shift
done

echo -e "$DEBUG_IDENTIFICATOR Build docker images"


${SCRIPTS_PATH}/docker_build -type droneclient

${SCRIPTS_PATH}/docker_build -type dronewebservice

# kubectl apply -f ${DEPLOYMENT_PATH}/dronewebservice/deployment.yaml --kubeconfig scripts/kube/config

# kubectl apply -f ${DEPLOYMENT_PATH}/droneclient/deployment.yaml --kubeconfig scripts/kube/config

# kubectl get deployments

echo -e "$DEBUG_IDENTIFICATOR Build kubernetes images"

echo -e "$DEBUG_IDENTIFICATOR End k8s building script"