#!/bin/bash

DEBUG_IDENTIFICATOR="[ \033[32m DEBUG \033[0m ]"
VERSION=$(cat VERSION)

echo -e "$DEBUG_IDENTIFICATOR Start k8s data config generation script"

echo -e "$DEBUG_IDENTIFICATOR Preparing system parameters"

ROOT_PATH=$(git rev-parse --show-toplevel)
KUBE_PATH=${ROOT_PATH}/scripts/kube
SCRIPTS_PATH=${ROOT_PATH}/scripts
KUBE_CONFIG_PATH=${ROOT_PATH}/config/kube

cd $SCRIPTS_PATH

mkdir kube

cd $KUBE_PATH

echo -e "$DEBUG_IDENTIFICATOR Generate ssl-files"

# Generate a private key
openssl genpkey -algorithm RSA -out client-key.pem

# Generate a certificate signing request (CSR)
openssl req -new -key client-key.pem -out client-csr.pem -subj "/C=US/ST=California/L=San Francisco/O=My Organization/CN=client.example.com"

# Self-sign the CSR to generate a client certificate
openssl x509 -req -in client-csr.pem -signkey client-key.pem -out client-cert.pem

# Convert the certificate and key to Base64-encoded data
openssl base64 -in client-cert.pem -out client-cert-base64.txt
openssl base64 -in client-key.pem -out client-key-base64.txt

cp ${KUBE_CONFIG_PATH}/config $KUBE_PATH

ls

cd $ROOT_PATH

echo -e "$DEBUG_IDENTIFICATOR End k8s data config generation script"