apiVersion: apps/v1
kind: Deployment
metadata:
  name: dronewebservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dronewebservice-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dronewebservice-deployment
    spec:
      containers:
      - name: dronewebservice-container
        image: dronewebservice:0.0.1
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
            - containerPort: 8101